import Head from 'next/head'

import { HomeSection } from '@/modules/Home'

import * as S from './indexStyles'

export default function Home() {
  return (
    <>
      <Head>
        <title>Rotas da UFPI CAFS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <S.HomeContainer>
        <HomeSection />
      </S.HomeContainer>
    </>
  )
}
