import Head from 'next/head'

import * as S from './indexStyles'
import { Container } from '@/commons/components'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <S.HomeContainer>
        <Container>
          <h1>Rotas da UFPI</h1>
          <p>Campus Amílcar Ferreira Sobral Floriano Piauí</p>
        </Container>
      </S.HomeContainer>
    </>
  )
}
